server:
  port: 8019
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.1.176
    port: 6379
    database: 0 # 数据库索引（0 - 15）
    timeout: 10000    # 连接超时时间（毫秒）
    lettuce: # lettuce 参数
      pool: # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        max-wait: -1 # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-idle: 5 # 最大空闲连接 默认为 8
        # 最小空闲连接 默认为 0

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  #关闭热部署重启
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  mvc: #开启过滤器可以让前端使用表单提交  好像让表单支持PUT operation等请求
    hiddenmethod:
      filter:
        enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


